### ISSUE TITLE
A specific stop is broken, what to do?

### ISSUE THREAD

**Issue by dexonter** [tofuSCHNITZEL/wienerlinien#4]
I am using the integration succesfully for over 2 months now and everything seems to work fine for the most part. I've added the 3 closest stops to me in YAML and... well, only 2 work well. These two work actually very well, with accuracy in seconds!

The third stop gives always bogus info, and is 100% unreliable (not even once it gave a good estimate about when the tram was coming). I tried adding it multiple times and still nothing.

Furthermore it does not match the readings from Wien Mobil App which tells me there is something else involved here potentially.

Please let me know what type of info you need, and I will make sure to post it here!

Thank you tofuSchnitzel!

**Comment by tofuSCHNITZEL** [comment]
please tell me the stopid you have issues with

**Comment by dexonter** [comment]
Thanks for replying! Sure, the stopID is 1741 (62 Rosenhügelstr. direction Oper)

**Comment by tofuSCHNITZEL** [comment]
this will be fixed in the next update. 1741 is for 62 and 58B so the data you see in HA is for the 58B.

**Comment by tofuSCHNITZEL** [comment]
please try the new beta version: https://github.com/tofuSCHNITZEL/home-assistant-wienerlinien/releases/tag/1.3.0-beta
(enable "show beta versions" under "redownload" in hacs)

**Comment by dexonter** [comment]
Thanks for this!

First impression: it does not work. Here is my code:

sensor:
 platform: wienerlinien
 firstnext: first
 stops:
 - 3790
 - 3761
 - 1741
 - stop: 1741
   line: 62
   firstnext: next

This creates two sensors for stop 1741 for 58B in both directions weirdly.... and none for stop 3761

In trying to fix this I've changed the code to:

sensor:
 platform: wienerlinien
 firstnext: first
 stops:
 - 3790
 - 3761
 - stop: 3761
   line: 58B
   firstnext: next
 - 1741
 - stop: 1741
   line: 62
   firstnext: next

Now I am getting a code error saying YAML expected 58B to be an integer...

Any advice on what to try? Thank you!

EDIT: just to be clear - before trying to change the code the second time I had sensors created for 3790 and 1741 for the wrong line in both directions and none for 3761

**Comment by tofuSCHNITZEL** [comment]
Please see the readme. The lineid is not the name of the line but an ID given by wienerlinen:

The Line ID you can get from the URL in your browser after selecting a Line on the site (https://till.mabe.at/rbl/?**line=301**) or in this csv: wienerlinien-ogd-linien.csv

**Comment by dexonter** [comment]
> Please see the readme. The lineid is not the name of the line but an ID given by wienerlinen:
> 
> The Line ID you can get from the URL in your browser after selecting a Line on the site (https://till.mabe.at/rbl/?**line=301**) or in this csv: wienerlinien-ogd-linien.csv

I see! I updated and there are no errors now but...

Is it possible that the sensors are not created because there are no buses/trams at this hour? Because I still do not see any sensor for 3761 and for 1741 I only see nightlines now...

**Comment by tofuSCHNITZEL** [comment]
Yes that could be. I thought about this case - but I have not had enough time yet to test it and figure out what the best course of action will be...
But I fear there is no real solution to this.... If you reload you ha at a time where a stop does not return any data - the sensor will not be added... Maybe I will replace it with a platform not ready exception instead so ha retries and eventually adds the sensor...
But then also the case needs to be handled if the sensor is already added and then in the night for example there is no data anymore... Will need more testing..

**Comment by dexonter** [comment]
No worries - that is really not a problem - well unless people like to restart their HA's during the night,,,, 

I can report back tomorrow about how it goes. Interestingly though I did get a sensor for 3790 (single line stop) with data: 'unavailable'

**Comment by tofuSCHNITZEL** [comment]
Hm weird, maybe it was already setup from "before"? Because currently 3790 also returns no monitors

**Comment by dexonter** [comment]
Perhaps the first time I restarted with the new beta version there was one last bus or something....

Eitherway, thank you for actively developing and troubleshooting this amazing tool!! I will give you all the feedback I can tomorrow after I see how it handles daytime.

I use this more than anything in HA for now...on my phone and on a tablet next to the front door of my apartment :)

**Comment by dexonter** [comment]
Good morning! New info available: it seems that with the new update you HAVE to add the lines to each stop or it will not create the sensors (so it's not optional). Then, all the sensors created in the past still remain as sensors - they are just "Unavailable" - this is potentially problematic when you try many combinations before you settle on a specific sensor config

Lastly, a question: how can I have sensors for both first and next departure? I deleted from the code the firstnext but still it generates only the first arrival (the rest are Unavailable, like I mentioned above)

**Comment by dexonter** [comment]
New update: the sensor for stop 3761 line 258 (58B) is not updating - last update is 8 hours ago when I restarted HA

stop 1741 & 3790 work fine

**Comment by tofuSCHNITZEL** [comment]
> Good morning! New info available: it seems that with the new update you HAVE to add the lines to each stop or it will not create the sensors (so it's not optional). Then, all the sensors created in the past still remain as sensors - they are just "Unavailable" - this is potentially problematic when you try many combinations before you settle on a specific sensor config

I tested it and not adding a line creates a sensor for the first monitor that is returned.
all the ones that are "unavailable" might be the old ones that were added before? (check out the entity name and if there is no line name in there its an "old" sensor) 

> Lastly, a question: how can I have sensors for both first and next departure? I deleted from the code the firstnext but still it generates only the first arrival (the rest are Unavailable, like I mentioned above)

you add it again e.g.:

```
sensor:
  platform: wienerlinien
  stops:
    - stop: 4429
      firstnext: first
    - stop: 4429
      firstnext: next
```

**Comment by tofuSCHNITZEL** [comment]
> New update: the sensor for stop 3761 line 258 (58B) is not updating - last update is 8 hours ago when I restarted HA
> 
> stop 1741 & 3790 work fine

I think since it was added when no monitor was available it will never work - I'm trying to find a way to fix this (have HA retrying until there is data and then add the sensor)

**Comment by dexonter** [comment]
> I tested it and not adding a line creates a sensor for the first monitor that is returned.
> all the ones that are "unavailable" might be the old ones that were added before? (check out the entity name and if there is no line name in there its an "old" sensor)

Well... I tested your theory and it did not work, once I deleted the info for the line - the sensor went "Unavailable"

Also all the "Unavailable" sensors are "new" sensors that have line numbers



> I think since it was added when no monitor was available it will never work - I'm trying to find a way to fix this (have HA retrying until there is data and then add the sensor)

stop 3761 line 258 (58B) did update when I restarted HA during the day....but it only updated itself once....



> > Lastly, a question: how can I have sensors for both first and next departure? I deleted from the code the firstnext but still it generates only the first arrival (the rest are Unavailable, like I mentioned above)
> 
> you add it again e.g.:
> 
> ```
> sensor:
>   platform: wienerlinien
>   stops:
>     - stop: 4429
>       firstnext: first
>     - stop: 4429
>       firstnext: next
> ```
 is there a way to make it the default for all lines to show both first and next rather than adding it manually to each line multiple times? something like firstnext: {first} or (next) or {both}

**Comment by dexonter** [comment]
After some months of testing the 1.3.0 beta version I can safely say that this isssue has been resolved
